# frozen_string_literal: true

require "open3"

module Hindsight
  # Writes HINDSIGHT.md for a built repository: where the code came from and
  # a table of contents, with the commits grouped into chapters by the test
  # file that drove them.
  class Story
    def initialize(project, out, record)
      @project = project
      @out = out
      @record = record
    end

    def render
      [header, toc].join("\n")
    end

    private

    def source_url
      url, = Open3.capture2("git", "-C", @project.root, "remote", "get-url", "origin")
      url.strip.sub(/\.git\z/, "").sub(%r{\Agit@github\.com:}, "https://github.com/")
    end

    def source_sha
      sha, = Open3.capture2("git", "-C", @project.root, "rev-parse", "HEAD")
      sha.strip
    end

    def header
      name = @project.name
      url = source_url
      sha = source_sha
      from = url.empty? ? name : "[#{name}](#{url})"
      at = url.empty? ? sha[0, 10] : "[`#{sha[0, 10]}`](#{url}/commit/#{sha})"
      <<~MD
        # About this repository

        This is a **synthetic git history** of #{from}, generated by
        [hindsight](https://github.com/techbelly/hindsight-ex) from commit #{at}.

        The code is the original authors' work and keeps its original licence (see
        LICENSE). Comments have been removed, since a generated history has no author
        whose remarks they would be. Only the commit history is fictional: hindsight
        recorded which lines each test executes, ordered the tests so each adds as
        little new code as possible, and replayed them one commit per test. Every
        commit was checked by running the tests present at that point. Read the log
        from the first commit forward to see how #{name} could have been built test by
        test.

        Each commit's subject is the test that drove it. Its body says what changed in
        code terms, lists other tests that started passing with it, and records how it
        was verified.
      MD
    end

    # Chapters: consecutive commits driven by tests from the same file.
    def toc
      log, = Open3.capture2("git", "-C", @out, "log", "--reverse", "--format=%h%x00%s%x00%b%x00%x01")
      commits = log.split("\x01").map { |c| c.strip.split("\x00") }.select { |c| c.size >= 3 }
      steps = commits.select { |_, _, body| body =~ /^Test: / }
      chapters = steps.chunk_while { |a, b| test_file(a) == test_file(b) }
      lines = ["## Contents", ""]
      lines << "#{steps.size} steps in #{chapters.count} chapters."
      lines << ""
      seen = Hash.new(0)
      chapters.each do |chapter|
        file = test_file(chapter.first)
        title = chapter_title(file)
        seen[title] += 1
        lines << "### #{title}#{' (continued)' if seen[title] > 1}"
        lines << ""
        chapter.each do |sha, subject, body|
          extra = body.scan(/^  .*\(test/).size
          lines << "- `#{sha}` #{subject}#{extra > 0 ? " (+#{extra} more)" : ''}"
        end
        lines << ""
      end
      lines.join("\n")
    end

    def test_file(commit) = commit[2][/^Test: (\S+?):/, 1]

    def chapter_title(file)
      base = File.basename(file.to_s, ".rb").sub(/_(test|spec)\z/, "").sub(/\A(test|spec)_/, "")
      base.split("_").map(&:capitalize).join(" ")
    end
  end
end
